global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: sample-job
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["some-service-in-docker-compose:8080"]
        labels:
          kubernetes_io_name: "some-service"
          kubernetes_pod_name: "some-service-1111111111-yyyyy"
      - targets: ["host.docker.internal:8080"]
        labels:
          kubernetes_io_instance: "locally-run-service"
          kubernetes_pod_name: "locally-run-service-2222222222-zzzzz"
